// Grupo de exalumnos, visto desde el teléfono de Mariana (capturas del 28-VI-2025, 17:1x).
const I = '../../../JUGADOR_GRATIS/E02/img/';
window.DATA = {
  titulo: '6°B Gen 94-2000 🎒',
  sub: 'Beto Macías, Itza, Karla DdL, Kevin Ruvalcaba, Nayeli Z., Óscar Mendoza, +21',
  hora: '5:12', bat: 63, grupo: true,
  colores: { 'Nayeli Z.': '#d62976', 'Beto Macías': '#e2710f', 'Karla DdL': '#7a4bd1', 'Itza': '#1b9b5b', 'Kevin Ruvalcaba': '#0f84c4', 'Óscar Mendoza': '#b3521f', 'Luisfer Durón': '#6b8e23' },
  m: [
    { day: 'Ayer' },
    { out: true, img: I + 'IMG-20250627-WA0012.jpg', cap: true, text: 'Así nos recibieron 🥹 la maestra del vespertino nos dejó el pintarrón escrito', time: '2:52 p. m.' },
    { from: 'Nayeli Z.', text: 'Qué bonitooo 😭', time: '2:55 p. m.' },
    { from: 'Beto Macías', text: '"Esta sigue siendo su casa" 🥲 ya me hizo llorar la maestra jajaja', time: '2:57 p. m.' },
    { from: 'Karla DdL', text: 'Gracias por organizar Mariana!! estuvo padrísimo', time: '3:01 p. m.' },
    { from: 'Luisfer Durón', text: 'Gracias Mari 👏👏 a ver cuándo la carnita asada', time: '3:02 p. m.' },
    { out: true, text: 'Ya llegué a mi casa. Las que se mojaron las estoy secando con la secadora 😂 les voy a ir mandando foto de su carta a los que me den permiso', time: '3:10 p. m.' },
    { out: true, img: '../_render/IMG-20250627-WA0014.jpg', cap: true, text: 'Y esta es la que les dije. Salió hasta el fondo de la caja, sin sobre, junto a los sobres que se deshicieron', time: '3:12 p. m.' },
    { out: true, text: '¿ALGUIEN SABE QUIÉN ES ITZEL? 🙏', time: '3:12 p. m.' },
    { from: 'Beto Macías', text: 'Itzayana confiesa 😂😂', time: '3:14 p. m.' },
    { from: 'Itza', text: 'Ay ya 🙄 la mía es la verde y la firmé Itza como siempre', time: '3:16 p. m.' },
    { out: true, img: I + 'IMG-20250627-WA0016.jpg', cap: true, text: 'Esta es la tuya Itza, quedó intacta 💚', time: '3:18 p. m.' },
    { from: 'Itza', text: 'Ayyy mi letra 😭 y el Canelo ya se murió', time: '3:19 p. m.' },
    { from: 'Karla DdL', text: '¿No sería del A? Mi prima iba en el 6° A y a veces se metían a nuestro salón en el recreo', time: '3:23 p. m.' },
    { from: 'Kevin Ruvalcaba', text: 'O de alguien que se cambió de escuela a medio año', time: '3:25 p. m.' },
    { from: 'Beto Macías', text: 'Yo me acuerdo que decían que en el edificio B se aparecía una niña en la noche 👻👻 a lo mejor es ella', time: '3:26 p. m.' },
    { from: 'Nayeli Z.', text: 'No manches Beto 😂 qué miedo', time: '3:27 p. m.' },
    { from: 'Beto Macías', del: 'Se eliminó este mensaje', time: '3:28 p. m.' },
    { from: 'Beto Macías', text: 'Oigan y la carta la hicimos en la casa no? yo me acuerdo que la hice en mi casa', time: '3:30 p. m.' },
    { out: true, text: 'No, en el salón, la maestra nos dio la hoja fotocopiada. Miren', time: '3:33 p. m.' },
    { out: true, img: I + 'IMG-20250627-WA0021.jpg', time: '3:33 p. m.' },
    { out: true, img: I + 'IMG-20250627-WA0022.jpg', time: '3:33 p. m.' },
    { from: 'Beto Macías', text: 'Pues yo me acuerdo en mi casa 🤷‍♂️', time: '3:34 p. m.' },
    { from: 'Karla DdL', text: 'Ay mis frenos 😂 qué oso', time: '3:36 p. m.' },
    { out: true, img: I + 'IMG-20250627-WA0031.jpg', cap: true, text: 'Le pedí a la maestra Chayo su lista del grupo. Somos 34 y no hay ninguna Itzel. La única parecida es Itzayana', time: '6:40 p. m.' },
    { from: 'Itza', text: 'YA LES DIJE QUE NO SOY YO 😤', time: '6:41 p. m.' },
    { from: 'Óscar Mendoza', text: 'Ni idea. ¿Ya salió la mía? Guárdenmela porfa, hasta diciembre voy a Ags', time: '7:02 p. m.' },
    { out: true, text: 'La tuya se mojó toda 😬 pero sí se lee, te la guardo', time: '7:05 p. m.' },
    { day: 'Hoy' },
    { out: true, text: 'Le mandé la foto a la maestra Chayo y ya me contestó con un audio. Se los paso', time: '4:30 p. m.' },
    { out: true, fw: true, audio: '1:28', time: '4:30 p. m.' },
    { from: 'Itza', text: 'Ya me etiquetaron en Facebook como 20 veces, ya les dije que no soy yo 🙃', time: '5:02 p. m.' },
    { out: true, text: 'Perdón 🙈 yo la publiqué para ver si alguien la conoce', time: '5:04 p. m.' },
    { from: 'Nayeli Z.', text: 'Pobre Itza jajaja', time: '5:05 p. m.' },
  ],
};
